version: '3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
    restart: unless-stopped
    networks:
      - linx-network

  data-loader:
    build:
      context: ./data-loader
    container_name: data-loader
    depends_on: 
      - postgres
    restart: unless-stopped
    networks:
      - linx-network

  catalog-api:
    build:
      context: ./catalog-api
    container_name: catalog
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on: 
      - postgres
    restart: unless-stopped
    networks:
      - linx-network

  recommender-api:
    build:
      context: ./recommender-api
    container_name: recommender
    expose:
      - 9000
    ports:
      - 9000:9000
    depends_on: 
      - catalog-api
    restart: unless-stopped
    networks:
      - linx-network    

networks: 
  linx-network:
    driver: bridge